on: push
name: Build & test on push
jobs:
  testOctodns:
    name: Test octodns
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test octodns
      uses: parkr/actions/docker-make@master
      with:
        args: test-octodns
