on:
  push:
    branches:
      - master
      - docker-push-test

name: Publish to Docker Hub on push to master
jobs:
  deployToDockerHub:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Login
      uses: parkr/actions/docker-auth@master
      with:
        args: login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
    - name: Publish octodns
      uses: parkr/actions/docker-make@master
      with:
        args: publish-octodns -e NAMESPACE=csteinbe
    - name: Docker Logout
      uses: parkr/actions/docker-auth@master
      with:
        args: logout
      env:
        DOCKER_REGISTRY_URL: docker.io
