on:
  push:
    branches: 
      - master
name: Publish to GitHub Package Registry on push to master
jobs:
  deployToGPR:
    name: On master branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: On master branch
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: GitHub Package Registry Login
      uses: parkr/dockerfiles/.github/actions/github-pkg-login@master
      env:
        GPR_PASSWORD: ${{ secrets.GPR_PASSWORD }}
        GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
    - name: Publish octodns to GitHub Package Registry
      uses: parkr/actions/docker-make@master
      with:
        args: publish-octodns-gpr
