on:
  push:
    branches: 
      - master
      - docker-push-test

name: Publish to GitHub Package Registry on push to master
jobs:
  deployToGPR:
    name: Deploy to GitHub Package Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GitHub Package Registry Login
      uses: parkr/actions/docker-auth@master
      with:
        args: login
      env:
        DOCKER_USERNAME: ${{ secrets.GPR_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.GPR_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.pkg.github.com
    - name: Publish octdns to GitHub Package Registry
    - uses: parkr/actions/docker-make@master
      with:
        args: publish-octodns -e NAMESPACE=docker.pkg.github.com/cjs/docker-octodns
          -e TAG_PREFIX=sha-
    - name: GitHub Package Registry Logout
      uses: parkr/actions/docker-auth@master
      with:
        args: logout
      env:
        DOCKER_REGISTRY_URL: docker.pkg.github.com

